In [9]:
#Create multi-dimensional arrays and find its shape and dimension 
import numpy as np
#Creation multi-dimensional arrays
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a)

print("shape:",a.shape)
print("dimension:",a.ndim)


[[1 2 3]
 [2 3 4]
 [3 4 5]]
shape: (3, 3)
dimension: 2


In [10]:
#Create a matrix full of zeros and ones
z=np.zeros((2,2))
print("zeros:",z)

o=np.ones((2,2))
print("ones:",o)


zeros: [[0. 0.]
 [0. 0.]]
ones: [[1. 1.]
 [1. 1.]]


In [11]:
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
b=a.reshape(4,2,2)
print("reshape:",b)

c=a.flatten()
print("flatten:",c)

reshape: [[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]
flatten: [1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


In [12]:
x=np.array([[10,20],[80,90]])
y=np.array([[30,40],[60,70]])
v=np.vstack((x,y))
print ("vertically:",v)

h=np.hstack((x,y))
print("horizontally:",h)

vertically: [[10 20]
 [80 90]
 [30 40]
 [60 70]]
horizontally: [[10 20 30 40]
 [80 90 60 70]]


In [13]:
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
temp=a[[0,1,2,3],[1,1,1,1]]
print("indexing",temp)

i=a[:4,::2]
print("slicing",i)


indexing [2 3 4 5]
slicing [[1 3]
 [2 4]
 [3 5]
 [4 6]]


In [17]:
a=np.array([[1,3,-1,4],[3,-2,1,4]])
b=a.min()
print("minimum:",b)
c=a.max()
print("maximum:",c)

#mean
x=np.array([1,2,3,4,5])
d= x.mean
print("mean:",d)

e=np.median(x)
print("median:",e)

f=x.std()
print("standard deviation:",f)

minimum: -2
maximum: 4
mean: <built-in method mean of numpy.ndarray object at 0x000001E106301270>
median: 3.0
standard deviation: 1.4142135623730951
