# 1. Create the following NumPy arrays: 

In [4]:
import numpy as np

In [118]:
# a) A 1-D array called zeros having 10 elements and all the elements are set to zero.
zeros = np.zeros(10,dtype=int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [119]:
# b) A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. # # b. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
vowels = np.array(['a','e','i','o','u'])
vowels

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [120]:
# c) A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and  dtype as int.
ones = np.ones((2,5),dtype=int)
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [121]:
# d) Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: i. 2.7, -2, -19, ii. 0, 3.4, 99.9, iii. 10.6, 0, 13 
myarray1 = np.array([[2.7, -2, -19],[0, 3.4, 99.9],[10.6, 0, 13]])
myarray1

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

In [122]:
# e) A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4,step size 4 and dtype as float.
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray2

array([[ 4.,  8., 12.],
       [16., 20., 24.],
       [28., 32., 36.]])

# Using the arrays created in the above, write NumPy commands for the following:

In [123]:
# a) Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels,ones, myarray1 and myarray2.
zeros.ndim

1

In [124]:
zeros.shape

(10,)

In [125]:
zeros.dtype

dtype('int32')

In [126]:
zeros.itemsize

4

In [127]:
vowels.ndim

1

In [128]:
vowels.shape

(5,)

In [129]:
vowels.size

5

In [130]:
vowels.dtype

dtype('<U1')

In [131]:
vowels.itemsize

4

In [132]:
ones.ndim

2

In [133]:
ones.shape

(2, 5)

In [134]:
ones.size

10

In [135]:
ones.dtype

dtype('int32')

In [136]:
ones.itemsize

4

In [137]:
myarray1.ndim

2

In [138]:
myarray1.shape

(3, 3)

In [139]:
myarray1.size

9

In [140]:
myarray1.dtype

dtype('float64')

In [141]:
myarray1.itemsize

8

In [142]:
myarray2.ndim

2

In [143]:
myarray2.shape

(3, 3)

In [144]:
myarray2.size

9

In [145]:
myarray2.dtype

dtype('float64')

In [146]:
myarray2.itemsize

8

In [147]:
# b) Reshape the array ones to have all the 10 elements in a single row. 
ones = np.ones((2,5),dtype=int)
ones.reshape(1,10)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [148]:
# c) Display the 2nd and 3rd element of the array vowels. 
print(vowels[1],vowels[2])

e i


In [149]:
# d) Display all elements in the 2nd and 3rd row of the array myarray1. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray1[1:3]

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

In [150]:
# e) Display the elements in the 1st and 2nd column of the array myarray1.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray1[0:3,0:2]

array([[ 2.7, -2. ],
       [ 0. ,  3.4],
       [10.6,  0. ]])

In [151]:
# f) Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
myarray1 = np.array([[2.7,-2,19],[0,3.4,99.9],[10.6,0,13]])
myarray1[1:3,0:3]

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

In [152]:
# g) Reverse the array of vowels.
vowels = np.array(['a','e','i','o','u'])
vowels[::-1]

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [153]:
# h) Divide all elements of array ones by 3. 
ones = np.ones((2,5),dtype=int)
ones/3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [154]:
# i) Add the arrays myarray1 and myarray2.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray1 + myarray2

array([[  6.7,   6. ,  -7. ],
       [ 16. ,  23.4, 123.9],
       [ 38.6,  32. ,  49. ]])

In [8]:
 # j) Subtract myarray1 from myarray2 and store the result in a new array
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
newarray=myarray2-myarray1
newarray

array([[  1.3,  10. ,  31. ],
       [ 16. ,  16.6, -75.9],
       [ 17.4,  32. ,  23. ]])

In [6]:
# k) Multiply myarray1 and myarray2 element wise. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray2 * myarray1

array([[  10.8,  -16. , -228. ],
       [   0. ,   68. , 2397.6],
       [ 296.8,    0. ,  468. ]])

In [157]:
# l) Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray3 = myarray2 @ myarray1
myarray3

array([[ 138. ,   19.2,  879.2],
       [ 297.6,   36. , 2006. ],
       [ 457.2,   52.8, 3132.8]])

In [158]:
# m) Divide myarray1 by myarray2. 
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray1 / myarray2

array([[ 0.675     , -0.25      , -1.58333333],
       [ 0.        ,  0.17      ,  4.1625    ],
       [ 0.37857143,  0.        ,  0.36111111]])

In [159]:
# n) Find the cube of all elements of myarray1 and divide the resulting array by 2.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarraycube = myarray1 ** 3
myarraycube/2

array([[ 9.841500e+00, -4.000000e+00, -3.429500e+03],
       [ 0.000000e+00,  1.965200e+01,  4.985015e+05],
       [ 5.955080e+02,  0.000000e+00,  1.098500e+03]])

In [160]:
# o) Find the square root of all elements of myarray2 and divide the resulting array by 2. The result should be rounded to two places of decimals.
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
arraysqrt = np.sqrt(myarray2)
newarraysqrt = arraysqrt/2
np.around(newarraysqrt,2)

array([[1.  , 1.41, 1.73],
       [2.  , 2.24, 2.45],
       [2.65, 2.83, 3.  ]])

In [161]:
# p) Find the transpose of ones and myarray2.
ones = np.ones((2,5),dtype=int)
ones.transpose()

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [162]:
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray2.transpose()

array([[ 4., 16., 28.],
       [ 8., 20., 32.],
       [12., 24., 36.]])

In [163]:
# q) Sort the array vowels in reverse. 
vowels = np.array(['a','e','i','o','u'])
vowels[ : : -1]

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [164]:
# r) Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.
myarray1 = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
myarray1.sort()
myarray1

array([[-19. ,  -2. ,   2.7],
       [  0. ,   3.4,  99.9],
       [  0. ,  10.6,  13. ]])

In [11]:
# s) Use NumPy. split() to split the array myarray2 into 5 arrays column wise. Store your resulting arrays in myarray2A, myarray2B, myarray2C, myarray2D and myarray2E. Print the arrays myarray2A, myarray2B, myarray2C, myarray2D and myarray2E
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray2A, myarray2B, myarray2C = np.split(myarray2,[1,3])
myarray2A,myarray2B,myarray2C

(array([[ 4.,  8., 12.]]),
 array([[16., 20., 24.],
        [28., 32., 36.]]),
 array([], shape=(0, 3), dtype=float64))

In [12]:
# t) Split the array zeros at array index 2, 5, 7, 8 and store the resulting arrays in zerosA, zerosB, zerosC and zerosD and print them.
zeros = np.zeros(10,dtype=int)
zerosnew = np.split(zeros,[2,5,7,8])
zerosA = zerosnew[0]
zerosB = zerosnew[1]
zerosC = zerosnew[2]
zerosD = zerosnew[3]

In [167]:
# u) Concatenate the arrays myarray2A, myarray2B and myarray2C into an array having 3 rows and 3 columns
myarray2 = np.arange(4,45,4,dtype=float)
myarray2.resize(3,3)
myarray2A, myarray2B, myarray2C = np.split(myarray2,[1,3])
np.concatenate((myarray2A, myarray2B, myarray2C),axis=0)

array([[ 4.,  8., 12.],
       [16., 20., 24.],
       [28., 32., 36.]])

In [168]:
# v) Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
np.split(myarray4,3,axis=1)

[array([[-1.  ],
        [-0.25],
        [ 0.5 ],
        [ 1.25],
        [ 2.  ],
        [ 2.75],
        [ 3.5 ],
        [ 4.25],
        [ 5.  ],
        [ 5.75],
        [ 6.5 ],
        [ 7.25],
        [ 8.  ],
        [ 8.75]]),
 array([[-0.75],
        [ 0.  ],
        [ 0.75],
        [ 1.5 ],
        [ 2.25],
        [ 3.  ],
        [ 3.75],
        [ 4.5 ],
        [ 5.25],
        [ 6.  ],
        [ 6.75],
        [ 7.5 ],
        [ 8.25],
        [ 9.  ]]),
 array([[-0.5 ],
        [ 0.25],
        [ 1.  ],
        [ 1.75],
        [ 2.5 ],
        [ 3.25],
        [ 4.  ],
        [ 4.75],
        [ 5.5 ],
        [ 6.25],
        [ 7.  ],
        [ 7.75],
        [ 8.5 ],
        [ 9.25]])]

# w) Using the myarray4 created in the above questions, write commands for the following: 

In [169]:
# i. Find the sum of all elements. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.sum()

173.25

In [170]:
# ii. Find the sum of all elements row wise.
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.sum(axis=1)

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  ])

In [171]:
# iii. Find the sum of all elements column wise. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.sum(axis=0)

array([54.25, 57.75, 61.25])

In [172]:
# iv. Find the max of all elements. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.max()

9.25

In [15]:
# v. Find the min of all elements in each row.
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.min(axis=1)

array([-1.  , -0.25,  0.5 ,  1.25,  2.  ,  2.75,  3.5 ,  4.25,  5.  ,
        5.75,  6.5 ,  7.25,  8.  ,  8.75])

In [174]:
# vi. Find the mean of all elements in each row. 
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.mean(axis=1)

array([-0.75,  0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,
        6.  ,  6.75,  7.5 ,  8.25,  9.  ])

In [117]:
# vii. Find the standard deviation column wise.
myarray4 = np.arange(-1,45,0.25,dtype=float)
myarray4.resize(14,3)
myarray4.std(axis=0)

array([3.02334666, 3.02334666, 3.02334666])