In [28]:
#Dot and matrix product of two arrays
import numpy.matlib 
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [27]:
#Compute the Eigen values of a matrix 
m = np.array([[1, 2],
              [2, 3]])
print(m)
w,v = np.linalg.eig(m)
print("Eigen values :",w)


[[1 2]
 [2 3]]
Eigen values : [-0.23606798  4.23606798]


In [7]:
#Solve a linear matrix equation such as 3 * x0+ x1= 9 and x0+ 2 * x1= 8
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
X = np.linalg.solve(A,B)

print(X)

[2. 3.]


In [21]:
#Compute the multiplicative inverse of a matrix 
m = np.matrix([[1, 6, 0], 
               [5, 8, 0], 
               [1, 0, 9]])
             
print( np.linalg.inv(m))

[[-0.36363636  0.27272727  0.        ]
 [ 0.22727273 -0.04545455  0.        ]
 [ 0.04040404 -0.03030303  0.11111111]]


In [24]:
#Compute the rank of a matrix 
rank = np.linalg.matrix_rank(m)
print("rank of the matrix is:",rank)

rank of the matrix is: 3


In [26]:
#Compute the determinant of an array
result =  np.linalg.det(m)
print("Determinant of  array:")
print(result)

Determinant of  array:
-198.00000000000017
